
# https://opennmt.net/OpenNMT-py/quickstart.html
# Examples in https://github.com/OpenNMT/OpenNMT-py/tree/master/config


## Where the samples will be written
save_data: ./runs
## Where the vocab(s) will be written
src_vocab: ./runs/cjhif.vocab.src
tgt_vocab: ./runs/cjhif.vocab.src
# Prevent overwriting existing files in the folder
overwrite: true
share_vocab: true

# Corpus opts:
data:
    corpus-1:
        path_src: ../data/cjhif/src-train.txt
        path_tgt: ../data/cjhif/tgt-train.txt
    valid:
        path_src: ../data/cjhif/src-val.txt
        path_tgt: ../data/cjhif/tgt-val.txt


# Train on a single GPU
world_size: 1
gpu_ranks: [0]

# Where to save the checkpoints
save_model: ./runs/models/cjhif
save_checkpoint_steps: 5000
keep_checkpoint: 3
train_steps: 200000
valid_steps: 10000
report_every: 100

tensorboard: true
tensorboard_log_dir: ./log_dir
